### ISSUE TITLE
[Integrate] As a user, I can see the multi choice question when taking a survey

### ISSUE THREAD

**Issue by ryan-conway** [nimblehq/flutter-ic-lydia-ryan#26]
## Why

App must display the multi choice question before taking a survey

## Acceptance Criteria

- Must display the multi choice question
- Must display question with `displayType` "choice"
- If `pick` is `one`, allow only single selection
- if `pick` is `any`, allow multi selection
- if `pick` is any other value, do not show question

## Resources

- [Design](https://www.figma.com/file/GjRPOjDyZ6f4EDL3wKarRK/Challenge---Mobile-App?node-id=34%3A1172)

**Comment by lydiasama** [comment]
I forgot to implement the single select. 🙈
