### ISSUE TITLE
[Chore] Set up code coverage tool

### ISSUE THREAD

**Issue by ryan-conway** [nimblehq/flutter-ic-lydia-ryan#4]
## Why

To ensure proper code coverage, we must set up [CodeCov](https://docs.codecov.com/docs)

## Acceptance Criteria

- [x] Follow the steps from the [CodeCov Quick Start guide](https://docs.codecov.com/docs/quick-start)
  ~- Workflows will be done in #5~
  - Workflow is done in #1

**Comment by lydiasama** [comment]
Added `CODECOV_TOKEN` in secret for [Dependabot](https://github.com/codecov/codecov-action) (The bot for Codecov github action)

![Image](https://user-images.githubusercontent.com/12026942/225505962-3cffadd0-1076-4b49-bc0f-8e574200ae6d.png)
